timesheet/urls.py
#from django.contrib.auth.decorators import login_required, permission_required
from django.conf.urls import url, include
from django.contrib.auth.decorators import login_required

from . import views


app_name = 'timesheet'

urlpatterns = [
	url('^', include('django.contrib.auth.urls')),
	url(r'^login/autenticar$', views.fazer_login, name = 'autenticar'),
	url(r'^login/sair$', views.fazer_logout, name = 'sair'),


	url(r'^$', login_required(views.DadosPessoaAutenticadaView.as_view()), name = 'dados_pessoa_autenticada'),
	url(r'^usuarios/$', login_required(views.ListaUltimasPessoasCadastradasView.as_view()), name = 'lista_ultimas_pessoas_cadastradas'),
    url(r'^usuarios/(?P<page>\d+)$', login_required(views.ListaPessoasView.as_view()), name = 'lista_pessoas'),
	url(r'^usuario/$', views.nova_pessoa, name = 'nova_pessoa'),
	# url(r'^usuario/(?P<pk>[0-9]+)$', views.editar_pessoa, name='editar_pessoa'),
	url(r'^usuario/(?P<pk>\d+)/visualizar$', login_required(views.VisualizarPessoaView.as_view()), name = 'visualizar_pessoa'),
	url(r'^usuario/(?P<pk>\d+)/remover', login_required(views.remover_pessoa), name = 'remover_pessoa'),
	url(r'^usuario/cadastrar$', views.cadastrar_pessoa, name = 'cadastrar_pessoa'),
	# url(r'^usuario/atualizar$', views.cadastrar_pessoa, name='atualizar_pessoa'),

]

timesheetmanager/urls.py
from django.conf.urls import include, url
from django.conf.urls.i18n import i18n_patterns, urlpatterns as i18n_urlpatterns
from django.contrib.admin import site as admin_site

from checklist.site import ChecklistSiteConfig
from history.site import HistoryEntrySiteConfig
from user.site import UserSiteConfig
from user.views import index


urlpatterns = i18n_patterns(
	url(r'^$', index),
	
	url(r'^i18n/', include(i18n_urlpatterns, namespace = 'language')),
	
    	url(r'^admin/', admin_site.urls),
    
	url(r'^user/', UserSiteConfig.as_include()),
	url(r'^history/', HistoryEntrySiteConfig.as_include()),
	url(r'^checklist/', ChecklistSiteConfig.as_include())

)

base/models.py
from django.db import models

base/forms.py
'''
Created on 13 de abr de 2016

@author: Leandro
'''
from django.conf.urls import url
from django.contrib import messages
from django.contrib.admin import models as log_models
from django.contrib.auth.mixins import AccessMixin
from django.contrib.contenttypes.models import ContentType
from django.core.exceptions import ImproperlyConfigured
from django.forms import models as model_forms
from django.utils.translation import ugettext_lazy as _lazy, ugettext as _
from django.views import generic
from django.views.generic.detail import SingleObjectTemplateResponseMixin

from history.models import HistoryEntry


class ProductivEnvBaseMixin(SingleObjectTemplateResponseMixin):
	context_object_name = "object"
	view_id = None
	view_name = None
	template_name_suffix = "_view"
	pattern = None

	@classmethod
	def as_url_import(self):
		return url(self.pattern, self.as_view(), name = self.view_id)

	def get_context_data(self, **kwargs):
		kwargs[self.context_object_name] = self.object
		kwargs["view_id"] = self.view_id
		if self.view_name:
			kwargs["view_name"] = self.view_name
		return super(ProductivEnvBaseMixin, self).get_context_data(**kwargs)

class ProductivEnvDetailView(ProductivEnvBaseMixin, generic.DetailView):
	template_name_suffix = "_detail"

class ProductivEnvModelFormView(ProductivEnvBaseMixin, generic.FormView):

	form_object_name = "object"
	fields = None
	model = None
	object = None
	is_update = None
	template_name_suffix = "_form"
	
	def get_current_object(self):
		form = self.get_form()
		if hasattr(form, self.form_object_name):
			return getattr(form, self.form_object_name)
		elif hasattr(form, "object"):
			return form.object
		elif hasattr(form, "instance"):
			return form.instance
		elif hasattr(self, self.form_object_name):
			return getattr(self, self.form_object_name)
		elif hasattr(self, "object"):
			return form.object
		elif hasattr(self, "instance"):
			return form.instance



	def get_form_class(self):
		"""
		Returns the form class to use in this view.
		"""
		if self.fields is not None and self.form_class:
			raise ImproperlyConfigured(
				"Specifying both 'fields' and 'form_class' is not permitted."
			)
		if self.form_class:
			return self.form_class
		else:
			if self.model is not None:
				# If a model has been explicitly provided, use it
				model = self.model
			elif hasattr(self, 'object') and self.object is not None:
				# If this view is operating on a single object, use
				# the class of that object
				model = self.object.__class__
			else:
				# Try to get a queryset and extract the model class
				# from that
				model = self.get_queryset().model

			if self.fields is None:
				raise ImproperlyConfigured(
                    "Using ModelFormMixin (base class of %s) without "
                    "the 'fields' attribute is prohibited." % self.__class__.__name__
                )

			return model_forms.modelform_factory(model, fields = self.fields)
	
	def get_form_kwargs(self):
		"""
		Returns the keyword arguments for instantiating the form.
		"""
		kwargs = super(ProductivEnvModelFormView, self).get_form_kwargs()
		if hasattr(self, 'object'):
			kwargs.update({'instance': self.object})
		return kwargs

	def get_content_type(self):
		if not self.content_type:
			self.content_type = ContentType.objects.get_for_model(self, self.model)
		return self.content_type

	def __validate_configuration(self):
		messages = []
		if not self.model:
			messages.append("model is not defined")
		if not self.view_id:
			messages.append("view id is not defined")
		if not self.pattern:
			messages.append("pattern is not defined")
		if messages:
			raise ImproperlyConfigured("ProductivEnvModelFormView is not properly configured because of: %s" % (", ".join(messages)))

	def get_user(self):
		return self.request.user

	def get_object(self, *args, **kwargs):
		self.__validate_configuration()
		if self.is_update is None:
			if not self.model:
				raise ImproperlyConfigured(_("The model atribute is required."))
			pk = kwargs.get("pk")
			if pk:
				self.is_update = True
				self.object = self.model.objects.get(**kwargs)
			else:
				self.is_update = False
				self.object = None
		return self.object

	def get(self, request, *args, **kwargs):
		self.__validate_configuration()
		self.object = self.get_object(*args, **kwargs)
		return super(ProductivEnvModelFormView, self).get(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		self.__validate_configuration()
		self.object = self.get_object(*args, **kwargs)
		return super(ProductivEnvModelFormView, self).post(request, *args, **kwargs)

	def form_commit(self):
		self.model.save(self.object)

	def form_valid(self, form):
		self.__validate_configuration()
		self.object = form.save(commit = False)
		self.form_commit()
		return super(ProductivEnvModelFormView, self).form_valid(form)

class ProductivEnvLogEntryMixin:

	def form_commit(self):
		user = self.get_user()
		if user:
			super(ProductivEnvLogEntryMixin, self).form_commit()
			content_type = ContentType.objects.get_for_model(model = self.model)
			action_flag = log_models.ADDITION
			change_message = "created"
			if self.is_update:
				action_flag = log_models.CHANGE
				change_message = "updated"
			log_models.LogEntry.objects.log_action(
					user_id = user.id,
					content_type_id = content_type.pk,
					object_id = self.object.id,
					object_repr = self.object.__str__(),
					action_flag = action_flag,
					change_message = change_message)
		else:
			raise ImproperlyConfigured("ProductivEnvLogEntryMixin must identify an user to log the action.")

class ProductivEnvHistoryEntryMixin:

	history_message_template = None

	def get_message_template(self):
		return self.history_message_template

	def get_message_parameters(self):
		return {"user_first_name": self.get_user().first_name}

	def form_commit(self):
		super(ProductivEnvHistoryEntryMixin, self).form_commit()
		HistoryEntry.objects.register_history_entry(
			user = self.get_user(),
			model_object = self.object,
			message = self.get_message_template(),
			parameters = self.get_message_parameters()
		)

class PermissionDeniedInfoMessageMixin(AccessMixin):
	message_template = _lazy("access denied, please provide the credentials of a user who has permission to %(message)s.")
	def handle_no_permission(self):
		message = self.get_permission_denied_message()
		if message:
			messages.info(self.request, self.message_template % { "message": message })
		return super(PermissionDeniedInfoMessageMixin, self).handle_no_permission()

class ViewIdMixin:
	view_id = None
	view_verbose_name = None

	def get_view_id(self):
		return self.view_id

	def get_view_verbose_name(self):
		return self.view_verbose_name

	def get_context_data(self, **kwargs):
		if hasattr(self, "get_context_data"):
			context_data = super(ViewIdMixin, self).get_context_data(**kwargs)
			view_id = self.get_view_id()
			if view_id:
				context_data["view_id"] = view_id
			view_verbose_name = self.get_view_verbose_name()
			if view_verbose_name:
				context_data["view_verbose_name"] = view_verbose_name
			return context_data
		else:
			raise ImproperlyConfigured(_("ViewIdMixin must be mixed with an class that has a 'get_context_data' method."))

class UpdateFormMixin:
	def get_object(self, *args, **kwargs):
		if not self.object:
			if not self.model:
				raise ImproperlyConfigured(_("The model atribute is required."))
			pk = kwargs.get("pk")
			if not pk:
				raise ImproperlyConfigured(_("A 'pk' kwarg is required."))
			return self.model.objects.get(**kwargs)
		return self.object

	def get(self, request, *args, **kwargs):
		self.object = self.get_object(*args, **kwargs)
		return super(BaseFormView, self).get(request, *args, **kwargs)

	def post(self, request, *args, **kwargs):
		self.object = self.get_object(*args, **kwargs)
		return super(BaseFormView, self).post(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		context = super(BaseFormView, self).get_context_data(**kwargs)
		context["object"] = self.object
		return context

class BaseFormView(generic.FormView):
	object = None
	model = None

	def before_save(self, instance):
		self.object = instance

	def after_save(self, instance):
		pass

	def form_valid(self, form):
		instance = form.save(commit = False)
		self.before_save(instance)
		self.model.save(instance)
		self.after_save(instance)
		return super(BaseFormView, self).form_valid(form)

timesheet/templates/timesheet/base.html
<!DOCTYPE html>
<html lang="en">
{% load staticfiles %}
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="../../favicon.ico">
<title>Timesheet Manager</title>
<!-- Bootstrap core CSS -->
<link href="{% static 'timesheet/dist/css/bootstrap.min.css' %}" rel="stylesheet">
<!-- Font Awesome core CSS -->
<link href="{% static 'timesheet/dist/css/font-awesome.min.css' %}" rel="stylesheet">
<!-- Custom styles for this template -->
<link href="{% static 'timesheet/css/base.css' %}" rel="stylesheet">
<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
	<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
	<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
{% block css_block %}{% endblock %}
</head>
<body>
	{% block body_block %}{% endblock %}
	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
	<script src="{% static 'timesheet/dist/js/bootstrap.min.js' %}"></script>
	{% block js_block %}{% endblock %}
</body>
</html>

timesheet/templates/timesheet/base_logged.html
{% extends 'timesheet/base.html' %} {% block body_block %}
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="{% url 'timesheet:dados_pessoa_autenticada' %}">
				<i class="fa fa-clock-o fa-lg"></i>
				Timesheet Manager
			</a>
		</div>
		<div id="navbar" class="navbar-collapse collapse">
			<ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<p class="navbar-text dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
						<i class="fa fa-user"></i>
						{{ user.first_name|default:user.get_username }}
						<i class="fa fa-caret-down"></i>
					</p>
					<ul class="dropdown-menu">
						<li>
							<p class="navbar-text">{{ user.get_full_name|default:user.get_username }}</p>
						</li>
						<li>
							<a href="{% url 'timesheet:sair' %}"><i class="fa fa-sign-out"></i> Sair</a>
						</li>
					</ul>
				</li>

			</ul>
			<ul class="nav navbar-nav">
				<li>
					<a href="{% url 'timesheet:dados_pessoa_autenticada' %}">
						<i class="fa fa-home"></i>
						Home
					</a>
				</li>
				<li>
					<a href="{% url 'timesheet:lista_pessoas' 1 %}">
						<i class="fa fa-users"></i>
						Usuários
					</a>
				</li>
				{% if user.is_authenticated and user.is_superuser %}
				<li>
					<a href="{% url 'admin:index' %}">
						<i class="fa fa-cogs"></i>
						Administração
					</a>
				</li>
				{% endif %}
				<!-- 					<div class="form-group"> -->
				<!-- 						<input type="text" placeholder="Email" class="form-control"> -->
				<!-- 					</div> -->
				<!-- 					<div class="form-group"> -->
				<!-- 						<input type="password" placeholder="Password" class="form-control"> -->
				<!-- 					</div> -->
				<!-- 					<button type="submit" class="btn btn-success">Sign in</button> -->
			</ul>
		</div>
	</div>
</nav>
<div class="container">
	<div class="hidden-xs hidden-sm base-top-margin-md-lg"></div>
	<div class="hidden-md hidden-lg base-top-margin-xs-sm"></div>
	{% block content_block %}{% endblock %}
	<hr>
	<footer>
		<p>&copy; 2015 Company, Inc.</p>
	</footer>
</div>
{% endblock %}

timesheet/templates/timesheet/base_public.html
{% extends 'timesheet/base.html' %}
{% block body_block %}
<nav class="navbar navbar-inverse navbar-fixed-top">
	<div class="container">
		<div class="navbar-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
				<span class="sr-only">Toggle navigation</span>
				<i class="fa fa-bars"></i>
			</button>
			<a class="navbar-brand" href="{% url 'timesheet:lista_ultimas_pessoas_cadastradas' %}">
				<i class="fa fa-clock-o fa-lg"></i>
				Timesheet Manager
			</a>
		</div>
	</div>
</nav>
<div class="container">
	<div class="hidden-xs hidden-sm base-top-margin-md-lg"></div>
	<div class="hidden-md hidden-lg base-top-margin-xs-sm"></div>
	{% block content_block %}{% endblock %}
	<hr>
	<footer>
		<p>&copy; 2015 Company, Inc.</p>
	</footer>
</div>
{% endblock %}

timesheet/templates/timesheet/pessoa_detail.html
{% extends 'timesheet/base_logged.html' %} {% block content_block %} {% load humanize %}
<h1 class="text-center">
	<i class="fa fa-user"></i>
	{% if user.get_username == pessoa.usuario.get_username %}
	Meus Dados
	{% else %}
	Detalhes do usuário {{ pessoa.usuario.first_name }}
	{% endif %}
</h1>
<hr />
<div class="row">
	<div class="col-md-4"></div>
	<div class="col-md-4">
		<div class="well well-lg">
			<p>
				<strong>Nome: </strong>
				{{ pessoa.usuario.get_full_name }}
			</p>
			<p>
				<strong>E-mail: </strong>
				{{ pessoa.usuario.email }}
			</p>
			<p>
				<strong>Login: </strong>
				{{ pessoa.usuario.username }}
			</p>
			<p>
				<strong>{{ pessoa.documento.tipo_documento.abreviacao }}: </strong>
				{{ pessoa.documento.codigo|mask:pessoa.documento.tipo_documento.mascara }}
			</p>
			<p>
				<strong>Cadastrado: </strong>
				{{ pessoa.usuario.date_joined|naturaltime }}
			</p>
			<p>
				<strong>Último login: </strong>
				{{ pessoa.usuario.last_login|naturaltime|default:"Ainda não autenticou." }}
			</p>
			<div class="clearfix"></div>
		</div>
		<a href="#" class="btn btn-primary">
			<i class="fa fa-pencil"></i>
			Editar
		</a>
		<button type="button" data-target="#confirmModal" data-toggle="modal" data-href="{% url 'timesheet:remover_pessoa' pessoa.id %}" data-nome="{{ pessoa.nome }}" class="btn btn-danger">
			<i class="fa fa-trash"></i>
			Remover
		</button>
		<a href="{% url 'timesheet:lista_pessoas' 1 %}" class="btn btn-default">
			<i class="fa fa-undo"></i>
			Voltar
		</a>
	</div>
	<div class="col-md-4"></div>
</div>

{% endblock %} {% block js_block %} {% include 'timesheet/includes/modal_remover_pessoa.html' %} {% endblock %}

timesheet/templates/timesheet/pessoa_form.html
{% extends 'timesheet/base_logged.html' %} {% block content_block %} {% load staticfiles %}
<h1 class="text-center">
	<i class="fa fa-user"></i>
	Formulário Usuário
</h1>
<hr />
<div class="row">
	{% if error_message %}
	<p>
		<strong>{{ error_message }}</strong>
	</p>
	{% endif %}
	<div class="col-md-4"></div>
	<form id="pessoa_form" class="col-md-4" action="{% url 'timesheet:cadastrar_pessoa' %}" method="post">
		{% csrf_token %}
		<div class="well well-lg">
			<div class="form-group col-md-12">
				<label for="nome">Primeiro Nome:</label>
				<input id="nome" class="form-control" type="text" name="primeiro_nome" value="{{ pessoa.usuario.first_name }}">
				<br>
			</div>
			<div class="form-group col-md-12">
				<label for="nome">Sobrenome:</label>
				<input id="nome" class="form-control" type="text" name="sobrenome" value="{{ pessoa.usuario.last_name }}">
				<br>
			</div>
			<div class="form-group col-md-12">
				<label for="nome">E-mail:</label>
				<input id="email" class="form-control" type="text" name="email" value="{{ pessoa.usuario.email }}">
				<br>
			</div>
			<div class="form-group col-md-4">
				<label for="tipo_documento">Documento:</label>
				<select id="tipo_documento" class="form-control" name="tipo_documento" value="{{ pessoa.documento.tipo_documento.id }}">
					{% for tipo_documento in tipos_documentos %}
					<option mask="{{ tipo_documento.mascara }}" value="{{ tipo_documento.id }}">{{ tipo_documento.abreviacao }}</option>
					{% endfor %}
				</select>
			</div>
			<div class="form-group col-md-8">
				<label for="codigo">&nbsp;</label>
				<input id="codigo" type="text" class="form-control" name="codigo" value="{{ pessoa.documento.codigo }}">
			</div>
			<div class="form-group col-md-12">
				<label for="login">Login:</label>
				<input id="login" class="form-control" type="text" name="login" value="{{ pessoa.usuario.username }}">
			</div>
			<div class="form-group has-feedback col-md-12">
				<label class="control-label" for="senha">Senha:</label>
				<input id="senha" class="form-control equals" type="password" name="senha">
				<i class="fa form-control-feedback"></i>
			</div>
			<div class="form-group has-feedback col-md-12">
				<label class="control-label" for="confirmar-senha">Confirmar Senha:</label>
				<input id="confirmar-senha" class="form-control equals" type="password" name="confirmar-senha">
				<i class="fa form-control-feedback"></i>
			</div>
			<div class="clearfix"></div>
		</div>
		<div class="form-group col-md-12">
			<button id="salvar" class="btn btn-primary" type="submit">
				<i class="fa fa-floppy-o"></i>
				Salvar
			</button>
			<a class="btn btn-default" href="{% url 'timesheet:lista_pessoas' 1 %}">
				<i class="fa fa-times"></i>
				Cancelar
			</a>
		</div>
	</form>
	<div class="col-md-4"></div>
</div>
{% endblock %} {% block js_block %}
<script src="{% static 'timesheet/dist/js/jquery.mask.min.js' %}"></script>
<script>
	(function($) {
		$(function() {
			var $form = $("#pessoa_form");
			applyMask(document.querySelector("#tipo_documento"));
			$form.on("blur", ".equals", function(e) {
				checkEqualsFields();
			});
			
			$form.on("change", "#tipo_documento", function(e) {
				applyMask(e.currentTarget);
			});

			$form.on("submit", function(e) {
				if (!checkEqualsFields()) {
					e.preventDefault();
				}
			});
		});
		function applyMask(combo) {
			var item = combo.value;
			var mask = "999999999999999999999999";
			for(i in combo.options) {
				var option = combo.options[i];
				if(option.value == item) mask = $(option).attr("mask");
			}
			$("#codigo").mask(mask.replace(/X/g, "9"));
		}
		
		function checkEqualsFields() {
			var $equals = $('.equals');
			var diff = false;
			var val;
			for (var i = 0; i < $equals.length; i++) {
				var field = $equals.get(i);
				if (!field.value) {
					diff = true;
					break;
				}
				if (val && field.value != val) {
					diff = true;
					break;
				}
				val = field.value;
			}

			if (diff) {
				$equals.parent().removeClass("has-success").addClass(
						"has-error").addClass("has-feedback").find(".fa")
						.removeClass("fa-check").addClass("fa-times");
			} else {
				$equals.parent().removeClass("has-error").addClass(
						"has-success").addClass("has-feedback").find(".fa")
						.removeClass("fa-times").addClass("fa-check");
			}
			return !diff;
		}
	}(jQuery));
</script>

{% endblock %}

timesheet/templates/timesheet/pessoa_list.html
{% extends "timesheet/base_logged.html"%} {% load humanize %} {% block content_block %}
<h1 class="text-center">
	<i class="fa fa-users"></i>
	Lista de Usuários
</h1>
<hr />
<div class="row">
	<a class="btn btn-primary" href="{% url 'timesheet:nova_pessoa' %}">
		<i class="fa fa-user"></i>
		<i class="fa fa-plus"></i>
		Cadastrar Usuário
	</a>
</div>
{% if is_paginated %}
<div class="row">{% include 'timesheet/includes/pagination.html' with href='timesheet:lista_pessoas' page_obj=page_obj %}</div>
{% else %}
<br />
{% endif %}
<div class="row">
	<div class="table-responsive">
		<table id="tabela" class="table table-bordered table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>ID</th>
					<th>Dados</th>
					<th>Data de Criação</th>
					<th>Último login</th>
					<th></th>
				</tr>
			</thead>
			<tbody>
				{% if object_list %} {% for pessoa in object_list %}
				<tr>
					<th>
						<strong>{{pessoa.id}}</strong>
					</th>
					<td>
						<i class="fa fa-user"></i>
						<strong>{{pessoa.usuario.get_full_name|capfirst|default:"Sem nome definido"}} ({{ pessoa.usuario.get_username }})</strong>
						<br />
						{{pessoa.documento.tipo_documento.abreviacao}}: {{pessoa.documento.codigo|mask:pessoa.documento.tipo_documento.mascara}}
					</td>
					<td>{{pessoa.usuario.date_joined|naturaltime}}</td>
					<td>{{pessoa.usuario.last_login|naturaltime|default:"Ainda não autenticou"}}</td>
					<td>
						<a class="btn btn-default btn-sm" href="{% url 'timesheet:visualizar_pessoa' pessoa.id %}">
							<i class="fa fa-eye"></i>
						</a>
						<button type="button" data-target="#confirmModal" data-toggle="modal" data-href="{% url 'timesheet:remover_pessoa' pessoa.id %}" data-nome="{{ pessoa.usuario.first_name }}"
							class="btn btn-default btn-sm">
							<i class="fa fa-trash"></i>
						</button>
					</td>
				</tr>
				{% endfor %} {% else %}
				<tr colspan="5">
					<p>Nenhum usuário cadastrado.</p>
				</tr>
				{% endif %}
			</tbody>
		</table>
	</div>
</div>
{% if is_paginated %}
<div class="row">{% include 'timesheet/includes/pagination.html' with href='timesheet:lista_pessoas' page_obj=page_obj %}</div>
{% endif %} {% endblock %} {% block js_block %} {% include 'timesheet/includes/modal_remover_pessoa.html' %} {% endblock %}